// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_INCLUDED_message_2eproto
#define PROTOBUF_INCLUDED_message_2eproto

#include <string>
#include <vector>
#include <google/protobuf/message.h>
#include <google/protobuf/stubs/common.h>

namespace chat {

// Forward declarations
class User;
class Friend;
class Group;
class OfflineMessage;
class LoginRequest;
class LoginResponse;
class RegisterRequest;
class RegisterResponse;
class OneChatMessage;
class AddFriendRequest;
class AddFriendNotify;
class AddFriendReply;
class AddFriendResult;
class CreateGroupRequest;
class CreateGroupResponse;
class AddGroupRequest;
class AddGroupResponse;
class GroupChatMessage;
class LoginoutRequest;
class LoginoutResponse;
class MessageWrapper;

// Enums
enum MsgType {
    LOGIN_MSG = 0,
    LOGIN_MSG_ACK = 1,
    REG_MSG = 2,
    REG_MSG_ACK = 3,
    ONE_CHAT_MSG = 4,
    ADD_FRIEND_MSG = 5,
    ADD_FRIEND_NOTIFY = 6,
    ADD_FRIEND_RESPONSE = 7,
    ADD_FRIEND_RESULT = 8,
    CREATE_GROUP_MSG = 9,
    ADD_GROUP_MSG = 10,
    GROUP_CHAT_MSG = 11,
    LOGINOUT_MSG = 12
};

// User message
class User : public ::google::protobuf::Message {
public:
    User();
    virtual ~User();
    
    // Accessors
    int32_t id() const { return id_; }
    void set_id(int32_t value) { id_ = value; }
    
    const std::string& name() const { return name_; }
    void set_name(const std::string& value) { name_ = value; }
    
    const std::string& password() const { return password_; }
    void set_password(const std::string& value) { password_ = value; }
    
    const std::string& state() const { return state_; }
    void set_state(const std::string& value) { state_ = value; }
    
    // Protobuf methods
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    int32_t id_;
    std::string name_;
    std::string password_;
    std::string state_;
};

// Friend message
class Friend : public ::google::protobuf::Message {
public:
    Friend();
    virtual ~Friend();
    
    int32_t id() const { return id_; }
    void set_id(int32_t value) { id_ = value; }
    
    const std::string& name() const { return name_; }
    void set_name(const std::string& value) { name_ = value; }
    
    const std::string& state() const { return state_; }
    void set_state(const std::string& value) { state_ = value; }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    int32_t id_;
    std::string name_;
    std::string state_;
};

// Group message
class Group : public ::google::protobuf::Message {
public:
    Group();
    virtual ~Group();
    
    int32_t id() const { return id_; }
    void set_id(int32_t value) { id_ = value; }
    
    const std::string& name() const { return name_; }
    void set_name(const std::string& value) { name_ = value; }
    
    const std::string& desc() const { return desc_; }
    void set_desc(const std::string& value) { desc_ = value; }
    
    const std::vector<User>& users() const { return users_; }
    User* add_users() { users_.push_back(User()); return &users_.back(); }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    int32_t id_;
    std::string name_;
    std::string desc_;
    std::vector<User> users_;
};

// AddFriendRequest message
class AddFriendRequest : public ::google::protobuf::Message {
public:
    AddFriendRequest();
    virtual ~AddFriendRequest();
    
    MsgType msgid() const { return msgid_; }
    void set_msgid(MsgType value) { msgid_ = value; }
    
    int32_t id() const { return id_; }
    void set_id(int32_t value) { id_ = value; }
    
    int32_t friendid() const { return friendid_; }
    void set_friendid(int32_t value) { friendid_ = value; }
    
    const std::string& message() const { return message_; }
    void set_message(const std::string& value) { message_ = value; }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    MsgType msgid_;
    int32_t id_;
    int32_t friendid_;
    std::string message_;
};

// AddFriendNotify message
class AddFriendNotify : public ::google::protobuf::Message {
public:
    AddFriendNotify();
    virtual ~AddFriendNotify();
    
    MsgType msgid() const { return msgid_; }
    void set_msgid(MsgType value) { msgid_ = value; }
    
    int32_t from_id() const { return from_id_; }
    void set_from_id(int32_t value) { from_id_ = value; }
    
    const std::string& from_name() const { return from_name_; }
    void set_from_name(const std::string& value) { from_name_ = value; }
    
    const std::string& message() const { return message_; }
    void set_message(const std::string& value) { message_ = value; }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    MsgType msgid_;
    int32_t from_id_;
    std::string from_name_;
    std::string message_;
};

// AddFriendReply message
class AddFriendReply : public ::google::protobuf::Message {
public:
    AddFriendReply();
    virtual ~AddFriendReply();
    
    MsgType msgid() const { return msgid_; }
    void set_msgid(MsgType value) { msgid_ = value; }
    
    int32_t from_id() const { return from_id_; }
    void set_from_id(int32_t value) { from_id_ = value; }
    
    int32_t to_id() const { return to_id_; }
    void set_to_id(int32_t value) { to_id_ = value; }
    
    bool accept() const { return accept_; }
    void set_accept(bool value) { accept_ = value; }
    
    const std::string& message() const { return message_; }
    void set_message(const std::string& value) { message_ = value; }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    MsgType msgid_;
    int32_t from_id_;
    int32_t to_id_;
    bool accept_;
    std::string message_;
};

// AddFriendResult message
class AddFriendResult : public ::google::protobuf::Message {
public:
    AddFriendResult();
    virtual ~AddFriendResult();
    
    MsgType msgid() const { return msgid_; }
    void set_msgid(MsgType value) { msgid_ = value; }
    
    int32_t errno_() const { return errno__; }
    void set_errno(int32_t value) { errno__ = value; }
    
    const std::string& errmsg() const { return errmsg_; }
    void set_errmsg(const std::string& value) { errmsg_ = value; }
    
    int32_t friend_id() const { return friend_id_; }
    void set_friend_id(int32_t value) { friend_id_ = value; }
    
    const std::string& friend_name() const { return friend_name_; }
    void set_friend_name(const std::string& value) { friend_name_ = value; }
    
    const std::string& reply_msg() const { return reply_msg_; }
    void set_reply_msg(const std::string& value) { reply_msg_ = value; }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    MsgType msgid_;
    int32_t errno__;
    std::string errmsg_;
    int32_t friend_id_;
    std::string friend_name_;
    std::string reply_msg_;
};

// OneChatMessage message
class OneChatMessage : public ::google::protobuf::Message {
public:
    OneChatMessage();
    virtual ~OneChatMessage();
    
    MsgType msgid() const { return msgid_; }
    void set_msgid(MsgType value) { msgid_ = value; }
    
    int32_t id() const { return id_; }
    void set_id(int32_t value) { id_ = value; }
    
    const std::string& name() const { return name_; }
    void set_name(const std::string& value) { name_ = value; }
    
    int32_t to() const { return to_; }
    void set_to(int32_t value) { to_ = value; }
    
    const std::string& msg() const { return msg_; }
    void set_msg(const std::string& value) { msg_ = value; }
    
    const std::string& time() const { return time_; }
    void set_time(const std::string& value) { time_ = value; }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    MsgType msgid_;
    int32_t id_;
    std::string name_;
    int32_t to_;
    std::string msg_;
    std::string time_;
};

// GroupChatMessage message
class GroupChatMessage : public ::google::protobuf::Message {
public:
    GroupChatMessage();
    virtual ~GroupChatMessage();
    
    MsgType msgid() const { return msgid_; }
    void set_msgid(MsgType value) { msgid_ = value; }
    
    int32_t id() const { return id_; }
    void set_id(int32_t value) { id_ = value; }
    
    const std::string& name() const { return name_; }
    void set_name(const std::string& value) { name_ = value; }
    
    int32_t groupid() const { return groupid_; }
    void set_groupid(int32_t value) { groupid_ = value; }
    
    const std::string& msg() const { return msg_; }
    void set_msg(const std::string& value) { msg_ = value; }
    
    const std::string& time() const { return time_; }
    void set_time(const std::string& value) { time_ = value; }
    
    const std::vector<int32_t>& users() const { return users_; }
    void add_users(int32_t value) { users_.push_back(value); }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    
private:
    MsgType msgid_;
    int32_t id_;
    std::string name_;
    int32_t groupid_;
    std::string msg_;
    std::string time_;
    std::vector<int32_t> users_;
};

// MessageWrapper message
class MessageWrapper : public ::google::protobuf::Message {
public:
    MessageWrapper();
    virtual ~MessageWrapper();
    
    MsgType msgid() const { return msgid_; }
    void set_msgid(MsgType value) { msgid_ = value; }
    
    const std::string& data() const { return data_; }
    void set_data(const std::string& value) { data_ = value; }
    
    bool SerializeToString(std::string* output) const override;
    bool ParseFromString(const std::string& data) override;
    std::string SerializeAsString() const { std::string result; SerializeToString(&result); return result; }
    
private:
    MsgType msgid_;
    std::string data_;
};

} // namespace chat

#endif // PROTOBUF_INCLUDED_message_2eproto
